[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scalla"]
  region = "eu-central-1"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
